# Para usar dockerfile es necesario modificar application.yml
# para realizar la conexion a MongoDb desplegado en Docker

mongo:
  image: "mongo"
  restart: always
  volumes:
    - './data:/data/db'
  ports:
    - "27017:27017"

app:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8081:8081"
  links:
    - mongo