spring:
  application:
    name: consultar-trm-colombia
  data:
    mongodb:
      #authentication-database: admin
      #username: root
      #password: root
      #database: TrmColombia
      #port: 27017
      #host: localhost
      uri: mongodb://localhost:27017/TrmColombia
server:
  port: 8081
