spring:
  application:
    name: consultar-trm-colombia
  thymeleaf:
    cache: true
  data:
    mongodb:
      #authentication-database: username
      #username: userdev
      #password: userdev123
      #database: trmcolombia
      #port: 62097
      #host: mongo  #(Activar para usar mongo-docker)
      uri: mongodb://userdev:userdev123@ds062097.mlab.com:62097/trmcolombia?retryWrites=false
server:
  port: 8081
